### ISSUE TITLE
 ErrorException  : DOMDocument::loadXML(): xmlParseEntityRef: no name in Entity, line: 9438

### ISSUE THREAD

**Issue by ghost** [mtownsend5512/xml-to-array#1]
Hi

I'm trying to read an invalid XML with your plugin and i'm receiving the error of why its invalid [xmlParseEntityRef: no name in Entity].

Is it possible to turn off this notification and parse it anyway?

Thanks!

**Comment by mtownsend5512** [comment]
Hi,

This sounds like it is an issue with the XML being invalid. More than likely it is due to a stray ``&`` character. You have a few different options:

1.  If you can control the xml, don't put unencoded ``&`` characters in it
2. You can also wrap the contents in CDATA tags, like so:

    ``<title><![CDATA[hello & goodbye]]></title>``
3. If you cannot control the xml, you can try running a preg_replace before you pass your xml into this package's parser.
    ``$xml = preg_replace('/&(?!#?[a-z0-9]+;)/', '&amp;', $xml);``
